import { env } from 'cloudflare:workers';
import type { Experiment } from '../engine/types.ts';
import { HttpError } from './security';
export function database(){const db=(env as unknown as {DB:D1Database}).DB;if(!db)throw new HttpError(503,'Experiment storage is unavailable');return db;}
export async function listExperiments(owner:string){const r=await database().prepare('SELECT id, name, status, created_at, updated_at, revision FROM experiments WHERE owner_id = ? ORDER BY created_at DESC LIMIT 100').bind(owner).all();return r.results;}
export async function loadExperiment(id:string,owner:string):Promise<Experiment>{const row=await database().prepare('SELECT payload FROM experiments WHERE id = ? AND owner_id = ?').bind(id,owner).first<{payload:string}>();if(!row)throw new HttpError(404,'Experiment not found');return JSON.parse(row.payload);}
export async function insertExperiment(e:Experiment,owner:string){await database().prepare('INSERT INTO experiments (id, owner_id, name, status, revision, payload, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').bind(e.id,owner,e.config.name,e.status,e.revision,JSON.stringify(e),e.createdAt,e.updatedAt).run();}
export async function acquireLease(id:string,owner:string,revision:number){const token=crypto.randomUUID();const now=Date.now();const r=await database().prepare('UPDATE experiments SET lease_token = ?, lease_until = ? WHERE id = ? AND owner_id = ? AND revision = ? AND (lease_until IS NULL OR lease_until < ?)').bind(token,now+120000,id,owner,revision,now).run();if(!r.meta.changes)throw new HttpError(409,'Another operation is running or this experiment changed. Refresh and try again.');return token;}
export async function saveExperiment(e:Experiment,owner:string,token:string){const previous=e.revision;e.revision++;const r=await database().prepare('UPDATE experiments SET status = ?, revision = ?, payload = ?, updated_at = ?, lease_token = NULL, lease_until = NULL WHERE id = ? AND owner_id = ? AND lease_token = ? AND revision = ?').bind(e.status,e.revision,JSON.stringify(e),e.updatedAt,e.id,owner,token,previous).run();if(!r.meta.changes)throw new HttpError(409,'Experiment lease changed; result was not saved');}
export async function releaseLease(id:string,owner:string,token:string){await database().prepare('UPDATE experiments SET lease_token = NULL, lease_until = NULL WHERE id = ? AND owner_id = ? AND lease_token = ?').bind(id,owner,token).run();}
export function publicExperiment(e:Experiment){const {contract,...config}=e.config;const {development,validation,test,...task}=contract;return{...e,config:{...config,contract:{...task,developmentCases:development.length,validationCases:validation.length,testCases:test.length}}};}
