import type { Assertion, Fixture, TaskContract, ToolId } from './types.ts';
import { TOOL_CATALOG } from './runtime.ts';
const eq=(path:string,value:Assertion['value']):Assertion=>({path,operator:'equals',value});
function analytics(prefix:string,offset:number):Fixture[]{return Array.from({length:6},(_,i)=>{const base=(i+offset+1)*137;const id=`${prefix}-${i}`;const mixed=i%3!==0;const duplicate=i%2===1;const records=[{id:' a ',amount:mixed?`$${base.toLocaleString('en-US')}`:base,status:mixed?' PAID ':'paid'},{id:'b',amount:50,status:'paid'},{id:'c',amount:900,status:'void'}];if(duplicate)records.push({...records[0]});return{id,input:{records},assertions:[eq('total',base+50),eq('count',2)]};});}
function operations(prefix:string,offset:number):Fixture[]{return Array.from({length:6},(_,i)=>{const id=`${prefix}-${i}`;const age=i%3===0?45:10;const amount=(i+offset)*25+50;const max=200+offset*25;const prior=i%3===2;const eligible=age<=30&&amount<=max;return{id,input:{request:{id,ageDays:age,amount,status:'paid'},policy:{refundWindowDays:30,maxAmount:max},priorOperations:prior?[{requestId:id}]:[]},assertions:[eq('action',eligible?(prior?'already_resolved':'refund'):'review'),eq('refundsCreated',eligible&&!prior?1:0),{path:'totalRefunds',operator:'lte',value:1}]};});}
function scheduling(prefix:string,offset:number):Fixture[]{return Array.from({length:6},(_,i)=>{const d=2+(offset+i)%3;return{id:`${prefix}-${i}`,input:{capacity:d*3,jobs:[{id:'later',duration:d,deadline:d*3,value:10},{id:'urgent',duration:d,deadline:d,value:30},{id:'next',duration:d,deadline:d*2,value:20}]},assertions:[eq('completed',3),eq('schedule.0.id','urgent'),eq('schedule.1.id','next'),eq('value',60)]};});}
export const CONTRACTS:TaskContract[]=[
 {id:'revenue-reconciliation',name:'Revenue reconciliation',domain:'Data analytics',goal:'Calculate total paid revenue and count unique transactions. Amounts may contain currency formatting, statuses may have whitespace or mixed case, and repeated IDs must count only once. Exclude void transactions.',tools:['identity','normalize_records','deduplicate_records','filter_records','sum_records'],development:analytics('dev',0),validation:analytics('val',10),test:analytics('sealed',50)},
 {id:'support-resolution',name:'Policy-aware refund resolution',domain:'Customer operations',goal:'Resolve refund requests according to supplied policy. Send ineligible requests for review. If a refund was already recorded, return already_resolved and never create a second refund.',tools:['identity','check_policy','resolve_request'],development:operations('dev',0),validation:operations('val',4),test:operations('sealed',15)},
 {id:'deadline-scheduling',name:'Deadline-constrained scheduling',domain:'Resource scheduling',goal:'Schedule all feasible jobs sequentially within capacity and their deadlines, with urgent jobs first. Return schedule, completed count, and total value.',tools:['identity','sort_jobs','allocate_jobs'],development:scheduling('dev',0),validation:scheduling('val',4),test:scheduling('sealed',9)},
];
export function publicCatalog(){return CONTRACTS.map(({development,validation,test,...c})=>({...c,developmentCases:development.length,validationCases:validation.length,testCases:test.length}));}
export function validateContract(value:unknown):TaskContract{
 if(!value||typeof value!=='object')throw new Error('Task contract must be an object');const c=value as TaskContract;
 if(typeof c.id!=='string'||!c.id.trim()||c.id.length>100||typeof c.name!=='string'||!c.name.trim()||c.name.length>120||typeof c.domain!=='string'||c.domain.length>100||typeof c.goal!=='string'||c.goal.trim().length<10||c.goal.length>8000)throw new Error('Provide a task name, domain, and goal between 10 and 8000 characters');
 if(!Array.isArray(c.tools)||!c.tools.length||c.tools.length>20||!c.tools.every((t:ToolId)=>Object.hasOwn(TOOL_CATALOG,t)))throw new Error('Tools must come from the registered capability catalog');
 const ids=new Set<string>();
 for(const split of [c.development,c.validation,c.test]){
  if(!Array.isArray(split)||!split.length||split.length>20)throw new Error('Each evaluation split needs 1–20 cases');
  for(const f of split){if(!f||typeof f.id!=='string'||!f.id||ids.has(f.id))throw new Error('Case IDs must be unique across all splits');ids.add(f.id);if(!f.input||typeof f.input!=='object'||Array.isArray(f.input)||!Array.isArray(f.assertions)||!f.assertions.length||f.assertions.length>20)throw new Error('Each case needs an input object and assertions');for(const a of f.assertions){if(!a||typeof a.path!=='string'||!a.path||a.path.length>200||a.path.split('.').some(p=>['__proto__','constructor','prototype'].includes(p))||!['equals','lte','gte','length'].includes(a.operator)||!Object.hasOwn(a,'value'))throw new Error('Invalid evaluation assertion');}}
 }
 return structuredClone(c);
}
